FROM python:3.11

WORKDIR /voicetracking_api

COPY . /voicetracking_api

RUN pip install --no-cache -r requirements.txt

# EXPOSE 7001

# CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "7001"]
