name: SSH with Password

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass and openssh-client
        run: sudo apt-get install -y sshpass openssh-client

      - name: Reset Git repository and pull latest changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ls; cd ~/radioapis; git reset --hard HEAD; git pull origin main; echo "${{ secrets.PASSWORD }}"

      - name: Create and start Docker Containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ls; cd ~/radioapis; echo "${{ secrets.PASSWORD }}" | sudo -S -u "${{ secrets.USERNAME }}" docker-compose up --build -d
